server:
  port: 9006
spring:
  application:
    name: tensquare_qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_spit?characterEncoding=UTF8
    username: root
    password: 123
  jpa:
    database: MySQL
    show-sql: true

